### ISSUE TITLE
[CUSTOM] CustomBookView

### ISSUE THREAD

**Issue by onpyeong** [TeamMascota/Mascota-Android#12]
## 💡 Issue
CustomBookView 

## 📝 todo
- [x] 책 모양 뷰 짜기
- [ ] left, right page attr 추가
- [ ] logo 뷰 짜기
- [ ] 일기 작성 뷰 짜기
- [ ] 일기 내용 뷰 짜기
