### ISSUE TITLE
[FEAT] 일기 작성 상세뷰 만들기 #7

### ISSUE THREAD

**Issue by ssonghyun101** [TeamMascota/Mascota-Android#18]
## 💡 Issue
DiaryDetailWriteFragment 완료하기

## 📝 todo
- [x] 뷰 짜기
- [ ] 사진 첨부 5장
- [x] 바텀 시트 다이얼로그로 사진 등록하기
- [x] 목차 선택 -> 목차 제목 띄우기
- [x] 날짜 픽커 -> 날짜 띄우기
- [x] 일기 작성하기
- [ ] 목차 선택, 날짜 선택, 일기 작성이 필수 -> 작성완료 버튼 활성화
- [ ] 맨 위 프로그래스바
