### ISSUE TITLE
[FEAT] ContentDetailActivity 중첩 RecyclerView 구현

### ISSUE THREAD

**Issue by onpyeong** [TeamMascota/Mascota-Android#20]
## 💡 Issue
ContentDetailActivity 구현 (swipe 버튼 제외)

## 📝 todo
- [ ]  아이템 뷰 짜기
    - [ ]  18일 금요일 따로 받기 하나의 textview
    - [x]  textview 최대 범위 지정
    - [x]  넘어가면 ...
    - [ ]  이미지 테두리 적용
    - [ ]  사진 없으면 invisible
- [x]  내부 리사이클러뷰
- [x]  월별 뷰 짜기
    - [x]  마진값
- [x]  외부 리사이클러뷰
- [ ]  전체 기초 뷰
- [ ]  로직 짜기
