### ISSUE TITLE
[FEAT] DiaryReadActivity 구현

### ISSUE THREAD

**Issue by onpyeong** [TeamMascota/Mascota-Android#27]
## 💡 Issue
DiaryReadActivity 구현

## 📝 todo
- [ ] top bar -> LinearLayout
- [ ] 이미지 
- [ ] Viewpager, 인디케이터
- [ ] 다음, 이전 버튼 연결
- [ ] 작성된 일기 텍스트
- [ ] 감정 띄우기
- [ ] 동물 사진 띄우기
