### ISSUE TITLE
[FEAT] CalendarFrgment 기초 세팅

### ISSUE THREAD

**Issue by mdb1217** [TeamMascota/Mascota-Android#3]
## 💡 Issue
CalendarFragment 기초 세팅 완료하기!

## 📝 todo
- [x] 뷰 세팅(캘린더 제외)
- [x] 로직 짜기(캘린더 제외)
- [x] dataSourceModule 만들기
- [x] dataSource 만들기(더미 데이터용)
