### ISSUE TITLE
[ADD] SignUpActivity 수정하기

### ISSUE THREAD

**Issue by ssonghyun101** [TeamMascota/Mascota-Android#56]
## 💡 Issue
 SignUpActivity 수정하기

## 📝 todo
- [x] 체크버튼 에셋 주기
- [x] 중복확인 에셋 주기
- [x] 회원가입 완료시 마스코타 이미지 맨 위에 넣기
- [x] 회원가입 완료 시 약관동의뷰 사라지기 
- [x] 비밀번호 체크뷰 배경색 삭제하기
- [x] 중복확인 비율 줄이기 
- [ ] 중복 확인 새로 만들기
