### ISSUE TITLE
[ADD] DiaryActivity 수정하기

### ISSUE THREAD

**Issue by ssonghyun101** [TeamMascota/Mascota-Android#57]
## 💡 Issue
DiaryActivity 수정하기

## 📝 todo
- [x] 디자인입히기
- [x] 빼기버튼 에셋 넣기
- [ ] 기분삭제 다이얼로그에 마스토카 다이얼로그 클래스에서 접근해서 수정하기 
- [x] 감정 이미지 에셋 적용하기
- [x]  고양이 감정 셀렉터 만들기
- [x] 목차선택뷰 디자인입히기
- [x] 스피너 다운버튼 에셋 입히기
- [x] 반려 동물 프로필뷰  디자인 입히기
- [x] 갤러리 버그 잡기 
- [ ] 사진 삭제 다시 넣기
- [x] 목차선택 구분선 없애기
- [x] 목차선택뷰 coner값 수정
