### ISSUE TITLE
[NETWORK] DiaryReadActivity 네트워크 연동

### ISSUE THREAD

**Issue by onpyeong** [TeamMascota/Mascota-Android#84]
## 💡 Issue
DiaryReadActivity 네트워크 연동

## 📝 todo
- [x] [GET] 1부 일기 조회 API
- [x] [GET] 1부 일기 삭제 API
- [ ] [GET] 2부 일기 조회 API
- [ ] [GET] 2부 일기 삭제 API
